### ISSUE TITLE
Rename `docs` or Move certain contents to a new repo

### ISSUE THREAD

**Issue by codeekage** [oscafrica/documentation#18]
IMHO it's a little bit misleading having the content of this repo with repo-name `docs`. The content of the repo is no ordinary documents but the representation of OSCA and should be in a repo with the name either : 
- admin 
- get-involved 
- osca 

It's difficult sorting for the GOVERNANCE.md and COC.md or even the logo folder in a docs repo. 

I suggest the name of the repo be changed or some contents moved to a new repo that improves the accessibility of the values of the community/project.

**Comment by samswag** [comment]
You need to be specific and maybe try to explain more. This repo was created to contain all "docs" related to OSCA so it will be easy to navigate. Moreover you can send a PR to fix then @Kolokodess and @Yomdroid can review.

**Comment by codeekage** [comment]
Generically, it makes sense to hop-into GitHub https://oscommunityafrica and locate the home directory that holds administrative and sensitive information (top-level detailed info) about the project in something like `@oscommunityafrica/osca`. <- immediately denotes into "that's the home directory".

**Comment by BolajiAyodeji** [comment]
Hi, @codeekage,

Thanks for this amazing feedback. We're revamping the entire documentation and we have put this into consideration. I'll be closing this for now.

Thank you :+1:
