### ISSUE TITLE
Gitbook not properly documented

### ISSUE THREAD

**Issue by samswag** [oscafrica/documentation#48]
Docs are now on gitbook.com; it will be great to properly document the process of how to contribute to it, so a contributor can understand how the syncing works.

**Comment by hqrshguptq** [comment]
Please help me with this. How could I just contribute?

**Comment by hqrshguptq** [comment]
Hi @samswag, @BolajiAyodeji  Please help me with this. How could I just contribute to the documentations for OSCA?

**Comment by chani24** [comment]
> Docs are now on gitbook.com; it will be great to properly document the process of how to contribute to it, so a contributor can understand how the syncing works.

Can you kindly explain further, i'll like to try and fix this issue.

**Comment by Anita-ihuman** [comment]
Can I tackle this issue?

**Comment by Code-Ebullient** [comment]
Is this issue still available? If yes.... Can i have the team/org link for the gitbook doc to look at it?

**Comment by BolajiAyodeji** [comment]
Closing this in favor of #81. Please join in there if you're interested in contributing further. Thank you.
