### ISSUE TITLE
Problem with base Readme file

### ISSUE THREAD

**Issue by honorezemagho** [oscafrica/Documentation#49]
Links are not showing 
There  are appearing like this {% page-ref page="about/introduction.md" %}

**Comment by Anita-ihuman** [comment]
Hello,
I’d like to take up this issue

**Comment by alabobriggs** [comment]
@Anita-ihuman We will be happy to have you work on it

**Comment by BolajiAyodeji** [comment]
Thanks for raising this @honorezemagho.

Actually, the links are not broken; our documentation is powered by GitBook while still connected to GitHub.
Those links are actually embeds used in the [main page](https://docs.oscafrica.org/) to callout some sub-pages, as seen in the image below:

![image](https://user-images.githubusercontent.com/30334776/213104442-dd79f4b5-c840-4f49-b15a-8b91fec309d0.png)

Thank you once again for your help, this docs is a WIP, and we'll document more about how to contribute to this project effectively soon.
