### ISSUE TITLE
Update README.md 

### ISSUE THREAD

**Issue by chryzcode** [oscafrica/Documentation#72]
There are invalid links in the readme file, inactive to lead people to an intended direction!  
  - I would love to ask if I can modify this and make a pull request
![oscafrica](https://user-images.githubusercontent.com/77321169/106850633-2cb36480-66b5-11eb-9f0d-12880df8e7be.jpg)
 - The [How can I Contribute Section]
   This only contains the guidelines to contribute but I feel there should also be a link directing people to the section they want to contribute to, either the documentation, engineering or the design section

**Comment by BolajiAyodeji** [comment]
Thanks for raising this, @chryzcode.

Actually, the links are not broken; our documentation is powered by GitBook while still connected to GitHub.
Those links are actually embeds used in the [main page](https://docs.oscafrica.org/) to callout some sub-pages, as seen in the image below:

![image](https://user-images.githubusercontent.com/30334776/213104442-dd79f4b5-c840-4f49-b15a-8b91fec309d0.png)

Thank you once again for your help, this docs is a WIP, and we'll document more about how to contribute to this project effectively soon.
