### ISSUE TITLE
Update summary.md

### ISSUE THREAD

**Issue by chryzcode** [oscafrica/documentation#73]
The summary has links that is to direct people well but there pages there that are blank and void and I feel if there is nothing to be documented there, such sections(links) should not be included because this causes frustration for people...trying to get information after navigating through pages and get to know there is nothing there!

### [The osca way](https://github.com/oscafrica/documentation/blob/master/about/the-osca-way/README.md)
 - [Values](https://github.com/oscafrica/documentation/blob/master/about/the-osca-way/values.md)
 - [Community guidelines](https://github.com/oscafrica/documentation/blob/master/about/the-osca-way/community-guidelines.md)
 - [Core Contributors Guidelines](https://github.com/oscafrica/documentation/blob/master/about/the-osca-way/core-contributors-guidelines.md)
 - [Core Contributors: Communication](https://github.com/oscafrica/documentation/blob/master/about/the-osca-way/core-contributors-communication.md)
 - [Core Contributors: Expenses](https://github.com/oscafrica/documentation/blob/master/about/the-osca-way/core-contributors-expenses.md)
- [OSCA Governance](https://github.com/oscafrica/documentation/blob/master/about/the-osca-way/governance.md)
## Others having same issue:
- PROJECTS
- INTERNAL
- COMMUNITY

and many more like that!

If I should be putting this down it would take a longer time, so I would rather stop here!

**Comment by BolajiAyodeji** [comment]
Hi @chryzcode, thanks for raising this. This documentation is a WIP, and as such, many pages are currently blank. We leave them as they are as temporary placeholders. We will resume working on improving the entire documentation soon. Thank you.

**Comment by BolajiAyodeji** [comment]
Kindly refer to #81 re my previous comment. I'll be closing this now while we continue tracking in the new issue. Thank you.
