### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by chryzcode** [oscafrica/Documentation#74]
Generally, the documentation of this great community lacking behind a bit and I feel the solution here is ;

## Solutions
1. There should be an announcement on this from the team
2. The community should be more active than before
3. More people should be involved, if possible admitting more members
4. The team should collaborate with people to give them the right information on things pertaining to the community

and many more!

**Comment by BolajiAyodeji** [comment]
Thank you for your suggestions. You're right, and we will work on bringing our documentation up to speed with the help of our community and contributors.
